-- MySQL Script generated by MySQL Workbench
-- Sat Jun  2 01:34:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clientes` (
  `id-clientes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id-clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedidos` (
  `id-pedidos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME(10) NULL,
  `id-cliente` INT NOT NULL,
  `id-producto` INT NOT NULL,
  `cantidad` INT NULL,
  `Clientes_id-clientes` INT NOT NULL,
  PRIMARY KEY (`id-pedidos`, `Clientes_id-clientes`),
  INDEX `fk_Pedidos_Clientes_idx` (`Clientes_id-clientes` ASC),
  CONSTRAINT `fk_Pedidos_Clientes`
    FOREIGN KEY (`Clientes_id-clientes`)
    REFERENCES `Clientes` (`id-clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Productos` (
  `id-producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Pedidos_id-pedidos` INT NOT NULL,
  `Pedidos_Clientes_id-clientes` INT NOT NULL,
  PRIMARY KEY (`id-producto`, `Pedidos_id-pedidos`, `Pedidos_Clientes_id-clientes`),
  INDEX `fk_Productos_Pedidos1_idx` (`Pedidos_id-pedidos` ASC, `Pedidos_Clientes_id-clientes` ASC),
  CONSTRAINT `fk_Productos_Pedidos1`
    FOREIGN KEY (`Pedidos_id-pedidos` , `Pedidos_Clientes_id-clientes`)
    REFERENCES `Pedidos` (`id-pedidos` , `Clientes_id-clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
